# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Sync files to AWS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: Sync files
      uses: AEnterprise/rsync-deploy@v1.0
      env:
        DEPLOY_KEY: ${{ secrets.SSH_KEY }}
        ARGS: "-e -c -r --delete"
        SERVER_PORT: ${{ secrets.SERVER_PORT }}
        FOLDER: "./"
        SERVER_IP: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USER }}
        SERVER_DESTINATION: ${{ secrets.FOLDER_PROD }}

